global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#evgeny_bratchenko'
