version: '3.3'

services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit-be:
        aliases:
          - comment_db

  ui:
    image: ${MYUSERNAME}/ui:${UI_VERSION}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${APPLICATION_EXT_PORT}:9292/tcp
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - reddit-fe

  post:
    image: ${MYUSERNAME}/post:${POST_VERSION}
    networks:
      - reddit-fe
      - reddit-be
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts

  comment:
    image: ${MYUSERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit-fe
      - reddit-be
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
      - COMMENT_DATABASE_HOST=comment_db
      - COMMENT_DATABASE=comments
      - APP_HOME=/app

volumes:
  post_db:
  prometheus_data:

networks:
  reddit-fe:
  reddit-be:
