version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      reddit-be:
        aliases:
          - comment_db
  ui:
    image: ${MYUSERNAME}/ui:${UI_VERSION}
    ports:
      - ${APPLICATION_EXT_PORT}:9292/tcp
    networks:
      - reddit-fe
  post:
    image: ${MYUSERNAME}/post:${POST_VERSION}
    networks:
      - reddit-fe
      - reddit-be
  comment:
    image: ${MYUSERNAME}/comment:${COMMENT_VERSION}
    networks:
      - reddit-fe
      - reddit-be
  prometheus:
    image: ${MYUSERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - reddit-fe
      - reddit-be
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - reddit-fe
      - reddit-be
  mongodb-exporter:
    image: ${MYUSERNAME}/mongodb-exporter:${MONGODB_EXPORTER_VERSION}
    networks:
      - reddit-fe
      - reddit-be
    environment:
      MONGODB_URI: 'mongodb://post_db:27017'
  blackbox-exporter:
    image: ${MYUSERNAME}/blackbox-exporter:latest
    ports:
      - '9115:9115'
    networks:
      - reddit-fe
      - reddit-be

volumes:
  post_db:
  prometheus_data:

networks:
  reddit-fe:
  reddit-be:
