version: '3'
services:
  fluentd:
    image: ${MYUSERNAME}/fluentd
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - reddit-fe
      - reddit-be

  elasticsearch:
    image: elasticsearch:7.5.0
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      - reddit-fe
      - reddit-be

  kibana:
    image: kibana:7.4.0
    ports:
      - 5601:5601
    networks:
      - reddit-fe
      - reddit-be

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - reddit-fe
      - reddit-be

networks:
  reddit-fe:
  reddit-be:
